CREATE TABLE SERHUMANO(
    ID VARCHAR2(100) NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF NUMBER(11) NOT NULL UNIQUE);
/
CREATE TABLE ENDERECO(
    SEQ NUMBER(2),
    SERHUMANO VARCHAR2(100) NOT NULL,
    RUA VARCHAR2(200) NOT NULL,
    NUMERO NUMBER(5) NOT NULL,
    BAIRRO VARCHAR2(50) NOT NULL,
    CIDADE VARCHAR2(50) NOT NULL,
    ESTADO VARCHAR2(2) NOT NULL,
    CEP NUMBER(8) NOT NULL,
    COMPLEMENTO VARCHAR2(150),
    CONSTRAINT PK_ENDERECO PRIMARY KEY (SEQ, SERHUMANO),
    CONSTRAINT FK_END_SERHUMANO FOREIGN KEY (SERHUMANO) REFERENCES SERHUMANO(ID));
/   
CREATE OR REPLACE TRIGGER TG_ENDERECO BEFORE INSERT 
    ON ENDERECO FOR EACH ROW
BEGIN
    SELECT NVL(MAX(SEQ), 0) + 1 INTO :NEW.SEQ 
    FROM ENDERECO 
    WHERE SERHUMANO_ID = :NEW.SERHUMANO_ID;
END;
/